### ISSUE TITLE
开源项目推荐: 记录肺炎

### ISSUE THREAD

**Issue by jilufeiyan** [WeileiZeng/Open-Source-COVID-19#10]
[记录肺炎]
(https://www.jilufeiyan.com/) 
给普通用户做的网站，用来记录逝者信息，希望能获得真实的死亡情况。

**其他留言**
为了尽可能保证上传消息的准确性，该项目需要申报人的个人信息。
同时，为了保护申报人的隐私，以及尊重死者隐私，该项目不会展示与身份证，住址，联系方式有关的信息。
之后这个项目会把非隐私数据公开，提供给大家下载也好，放到github上也好，只要能有个地方记录逝去的人就行。

**Comment by WeileiZeng** [comment]
谢谢，已经添加！

之前忘记回复了，不好意思！

**Comment by jilufeiyan** [comment]
> 谢谢，已经添加！
> 
> 之前忘记回复了，不好意思！

要谢谢你才是！
