### ISSUE TITLE
site recommendation: coronawhy

### ISSUE THREAD

**Issue by memetics19** [WeileiZeng/Open-Source-COVID-19#100]
- repo_name:https://github.com/CoronaWhy
  repo2_name:
  web_name: CoronaWhy
  web_url:https://www.coronawhy.org/

which area the projects is working on? Global or some particular area?
Global

**Comment by WeileiZeng** [comment]
Thanks added.

**Comment by memetics19** [comment]
Please add Coronawhy in the list of CORD-ID and research and development sections. We are working on AI literature tool.

**Comment by WeileiZeng** [comment]
Thanks for the correction. It is fixed.
