### ISSUE TITLE
开源项目推荐: 日本新冠肺炎感染速报

### ISSUE THREAD

**Issue by swsoyee** [WeileiZeng/Open-Source-COVID-19#11]
**请用如下格式填写，每条目各占一行，替换或者删除对应条目，谢谢**
[仓库名称] 2019-ncov-japan
(仓库链接) https://github.com/swsoyee/2019-ncov-japan
[项目名称] 新型コロナウイルス感染速報
(项目网站链接) https://covid-2019.live/
项目描述

记录日本新冠肺炎发展情况的Dashboard。

**其他留言**
这是我个人开发维护的项目，采用实时更新的方式追踪日本最新感染者确认情况。
项目还在持续开发维护中。
案例数据来源于日本厚生労働省，实时数据采用日本各大媒体的新闻报道进行统计。
分类方法和NHK一致，每日进行多次数据核对。

**Comment by WeileiZeng** [comment]
谢谢！我们添加了world板块，已收录其中。
