### ISSUE TITLE
开源项目推荐: COVID-19 Coronavirus Map

### ISSUE THREAD

**Issue by stevenliuyi** [WeileiZeng/Open-Source-COVID-19#15]
- repo_name: [stevenliuyi/covid19](https://github.com/stevenliuyi/covid19)
  web_name: COVID-19 Coronavirus Map / 新型冠状病毒肺炎疫情图
  web_url: https://covid19.health
  content: an interactive, animated COVID-19 coronavirus map

这项目是我个人在维护，主要是追踪各个国家以及部分国家（目前有中国、韩国、意大利）各地区疫情的发展情况。

**Comment by WeileiZeng** [comment]
谢谢，已添加。
