### ISSUE TITLE
Site recommendation: coronaviruslive.it

### ISSUE THREAD

**Issue by coronavirusliveitalia** [WeileiZeng/Open-Source-COVID-19#18]
- repo_name: sasso0101/coronavirus
  web_name: Coronaviruslive italia
  web_url: https://coronaviruslive.it/
  content: A dashboard of the active cases, death and recovered cases in Italy. The site includes also historical data and is constantly updated.

**Comment by WeileiZeng** [comment]
Thanks! Added!
