### ISSUE TITLE
Recommendation: Corona Tracker for iOS

### ISSUE THREAD

**Issue by MhdHejazi** [WeileiZeng/Open-Source-COVID-19#19]
- repo_name: https://github.com/MhdHejazi/Corona
  content: Coronavirus tracker app for iOS with maps & charts.

**Comment by WeileiZeng** [comment]
Thanks! Added!.

This seems to be a developer version. If you have a published version, I would be happy to add a link.

**Comment by MhdHejazi** [comment]
Thanks for the quick response!

I wish I could publish it on the app store, but [Apple is rejecting coronavirus apps that aren’t from health organizations](https://www.cnbc.com/2020/03/05/apple-rejects-coronavirus-apps-that-arent-from-health-organizations.html).

**Comment by WeileiZeng** [comment]
I understand it is always tricky with apple store.
