### ISSUE TITLE
site recommendation: open_covid19

### ISSUE THREAD

**Issue by jpoles1** [WeileiZeng/Open-Source-COVID-19#20]
**Please use the following format. You can leave any of them blank. Thanks**
- repo_name: open_covid19
  web_url: https://github.com/jpoles1/open_covid19
  content: A Jupyter notebook with basic COVID-19 outbreak modeling. Use it to get started with your own analysis! Updates daily using data from Johns Hopkins University Center for Systems Science and Engineering.

**Comment by WeileiZeng** [comment]
Thanks! Added!
