### ISSUE TITLE
开源项目推荐: 项目名称 or (site recommendation: project name)

### ISSUE THREAD

**Issue by coronafighter** [WeileiZeng/Open-Source-COVID-19#22]
**请用如下格式填写，每条目各占一行，若无对应条目请空置或者删除，谢谢**
**Please use the following format. You can leave any of them blank. Thanks**
- repo_name: coronafighter/coronaSEIR
  web_name: COVID-19 Python SEIR model and data plot
  web_url: https://github.com/coronafighter/coronaSEIR
  web2_name:
  content: Simple SEIR model Python script for the COVID-19 pandemic with real world data comparison.

例如：example:
- repo_name: WeileiZeng/OpenSourceWuhan
    web_name: 武汉开源OpenSourceWuhan
    web_url: https://weileizeng.github.io/OpenSourceWuhan/
    content: A collection of all Open Source project for defending Wuhan/world during COVID-19 支援武汉开源项目汇总

**Comment by WeileiZeng** [comment]
awesome Thanks! Added!
