### ISSUE TITLE
Consider making /world the homepage

### ISSUE THREAD

**Issue by audreyr** [WeileiZeng/Open-Source-COVID-19#23]
Open-Source-COVID-19 is currently the most comprehensive list of open-source COVID-19 projects that I've found anywhere. Great work!

Just a little suggestion: consider making /world the homepage and making /china its own page, to attract more international collaborators 🙂

**Comment by WeileiZeng** [comment]
Thanks! Good idea! I will switch it in next update.

Now world page has double visit compared with the homepage/china. Meanwhile, I just notice that github.io is not so friendly in China, which require ~10 secs to open the page there.

**Comment by WeileiZeng** [comment]
done! check it out. Now I use the homepage and chain page. The world page is saved for compatibility.
Thanks for the suggestion!
