### ISSUE TITLE
OpenSourceHeroes

### ISSUE THREAD

**Issue by WeileiZeng** [WeileiZeng/Open-Source-COVID-19#25]
My next idea is to add a page for the people who contributed to the open source community during this outbreak.

Processing by hand would be very hard for this subject. But luckily there are github api allowing you to grab all repos or github users related to the keywords, like nCoV or COIVD. Then we can do some statistics.

If any one would be interested to add that part, it would be great! And I will be very happy to add it to the website.

**Comment by divy-work** [comment]
Sure @WeileiZeng 
I think we can do that by following these steps:

* Get the repository list using the GitHub search API

```
curl https://api.github.com/search/repositories?q=covid19
```

* Then retrieve info of their owners and display it on a page.

**Comment by WeileiZeng** [comment]
Good suggestion! That is what I thought as well. I did something in this folder
https://github.com/WeileiZeng/Open-Source-COVID-19/tree/master/src/heroes
the result is on this page
https://weileizeng.github.io/Open-Source-COVID-19/heroes

My idea is to focus on contributors instead of repo here. Haven't think through the layout and what data to show yet. It will also take some time to code as well. If you are familiar with python and json, you are welcome to tracker the data, play with it, and output to a json table. I will be able to show the json in a web format.

**Comment by divy-work** [comment]
Sure I can try doing that!

**Comment by WeileiZeng** [comment]
Great! Thanks!
To ease the work of compatibility
* I am always using python3 and pip3. The main difference is [print 'hello'] doesn't work in python3
* json may have problem with emoji. Some repos have emoji in their descriptions. Sometimes it may produce a reading problem, but not in all cases. Just let me know if same issue occurs.
* I can use github action to run python script regularly, like 8 am everyday or at every push. So this can handle the updating part, once everything is ready.
Thanks again!

**Comment by divy-work** [comment]
Yes @WeileiZeng I've worked previously with Py3 :)
Sounds great, I've opened a PR #35

**Comment by WeileiZeng** [comment]
not actively right now, hence temporarily close.
