### ISSUE TITLE
Suggestion - Search Tool:  Open-Source-COVID-19

### ISSUE THREAD

**Issue by ThomasThelen** [WeileiZeng/Open-Source-COVID-19#27]
- repo_name:Open-Source-COVID-19
  web_name: Open-Source-COVID-19
  web_url: https://weileizeng.github.io/Open-Source-COVID-19/
  content: Now that the list has grown and continues to grow, it would be cool to see a tool that researchers or open source contributors can use to find what they're after. Since the site is hosted on GitHub, it should be possible to use Javascript to parse the yaml files and display relevant items.

It would probably be something like.... 
```
projects = []
for each yaml file:
    projects.append(yaml file)
shownProjects = projects
```
And then each time someone does a filter, `shownProjects` is updated.

Edit: This could piggy back off of that other issue you had filed [here](https://github.com/soroushchehresa/awesome-coronavirus/issues/2#issuecomment-598522056). In particular, the tags would be exposed in a dropdown menu, which would make filter super easy.

**Comment by WeileiZeng** [comment]
Sounds very good. I will put this in my next update.
* I can render freely between yaml and json, so this should make the data approachable for most people. I can save a json version in the meantime.
* I use jekyll to build the website, which uses Liquid to render the yaml data. So I can show the list in any order, as long as I have the tags.
* I can also add a search page, to search for some keyword. (not sure if this is necessary, cause one can just use Ctrl+F)
I will see if I can do it over the weekend. Sounds some work to rearrange these.

**Comment by WeileiZeng** [comment]
I realize adding the tags is as much work as the coding part, if not more. If anyone would like to add tags to the existing projects, that would be great! One projects could have multiple tags, like
- map
- data
- API
- analysis
- Apps
etc

**Comment by WeileiZeng** [comment]
The list of global projects grows very quickly and may need more detailed classification. But I doubt some of them (especially those crowdsourcing list ) may only belong to US. Because I live here and many people who build their site may not claim that it is US only.

**Comment by WeileiZeng** [comment]
I just added more tags
https://weileizeng.github.io/Open-Source-COVID-19/

**Comment by WeileiZeng** [comment]
now the tags are shown in yellow in the end of each project

**Comment by WeileiZeng** [comment]
http://open-source-covid-19.weileizeng.com/tags

add a beta page for listing projects by tags

**Comment by paras-jain** [comment]
for search utility you can into meilisearch, its good and fast and easy to use.

**Comment by WeileiZeng** [comment]
> for search utility you can into meilisearch, its good and fast and easy to use.

Our page is on github pages. Not sure how to deploy it. Can it be rendered as a static html page?

**Comment by paras-jain** [comment]
oh, had completely forgotten about that, perhaps not.
