### ISSUE TITLE
开源项目推荐: 项目名称 or (site recommendation: project name)

### ISSUE THREAD

**Issue by agarrone** [WeileiZeng/Open-Source-COVID-19#30]
**请用如下格式填写，每条目各占一行，若无对应条目请空置或者删除，谢谢**
**Please use the following format. You can leave any of them blank. Thanks**
- repo_name: opencovid19-fr
  repo2_name:
  web_name: https://veille-coronavirus.fr/
  web_url: https://github.com/opencovid19-fr
  web2_name:
  web2_url:
  content: French project that aims to consolidate official informations, and making it available in open and easily reusable formats. The project also provides a dashboard.

例如：example:
- repo_name: WeileiZeng/OpenSourceWuhan
    web_name: 武汉开源OpenSourceWuhan
    web_url: https://weileizeng.github.io/OpenSourceWuhan/
    content: A collection of all Open Source project for defending Wuhan/world during COVID-19 支援武汉开源项目汇总

**Comment by agarrone** [comment]
Hello, 

This is a French repo, a new category needs to be created. 

Many thanks !

**Comment by WeileiZeng** [comment]
Great! Added!
