### ISSUE TITLE
yiqin项目地图域名更改

### ISSUE THREAD

**Issue by laomocode** [WeileiZeng/Open-Source-COVID-19#34]
你好，开发者！
由于[yiqin](https://github.com/laomocode/yiqin)原理从原来的通过Github Actions自动化上传到腾讯云的COS上变为改用腾讯云的云函数，以达到实时的目的。同时域名也从wuhan.zw2s.ltd改为yiqin.zw2s.ltd。
希望开发者看见后能及时更改

**Comment by WeileiZeng** [comment]
谢谢，已经更新！

建议修改一下html title
Awesome-pyecharts 改成类似“疫情地图”

**Comment by laomocode** [comment]
已修改，谢谢
