### ISSUE TITLE
site recommendation: Coronavirus-modelling

### ISSUE THREAD

**Issue by Eddie-yz** [WeileiZeng/Open-Source-COVID-19#36]
**请用如下格式填写，每条目各占一行，若无对应条目请空置或者删除，谢谢**
**Please use the following format. You can leave any of them blank. Thanks**
- repo_name: Eddie-yz/Coronavirus-modelling
  web_url: https://github.com/Eddie-yz/Coronavirus-modelling
  content: using dynamic SEIR model which considers the parameters changing through time to fit data.

**Comment by WeileiZeng** [comment]
Great work! Which country or region is it working on right now?

**Comment by Eddie-yz** [comment]
> Great work! Which country or region is it working on right now?

Mainly using the data from Zhejiang province.

**Comment by Eddie-yz** [comment]
sorry, I just closed it by mistake.

**Comment by WeileiZeng** [comment]
> > Great work! Which country or region is it working on right now?
> 
> Mainly using the data from Zhejiang province.

Sounds good. I suggestion you claim this clear in your readme. People may need this for reference.

I will put your project in the China page, data analysis section.

**Comment by Eddie-yz** [comment]
> > > Great work! Which country or region is it working on right now?
> > 
> > 
> > Mainly using the data from Zhejiang province.
> 
> Sounds good. I suggestion you claim this clear in your readme. People may need this for reference.
> 
> I will put your project in the China page, data analysis section.

Sure. Actually I have mentioned it in the _Result Comparison_ part of the readme, but I will update it to make things more clear. Thanks for ur advice.

**Comment by WeileiZeng** [comment]
Added.
