### ISSUE TITLE
开源项目推荐: 项目名称 or (site recommendation:OpenIntubator)

### ISSUE THREAD

**Issue by brentjackson** [WeileiZeng/Open-Source-COVID-19#40]
**请用如下格式填写，每条目各占一行，若无对应条目请空置或者删除，谢谢**
**Please use the following format. You can leave any of them blank. Thanks**
- repo_name: OpenIntubator
  repo2_name:
  web_name:
  web_url: https://github.com/brentjackson/OpenIntubator/wiki
  web2_name:
  web2_url:
  content: An open source hardware project to develop intubation kits needed to support medical professionals.

例如：example:
- repo_name: WeileiZeng/OpenSourceWuhan
    web_name: 武汉开源OpenSourceWuhan
    web_url: https://weileizeng.github.io/OpenSourceWuhan/
    content: A collection of all Open Source project for defending Wuhan/world during COVID-19 支援武汉开源项目汇总

**Comment by WeileiZeng** [comment]
Thanks! Added!

**Comment by WeileiZeng** [comment]
There are some similar site in the list, which might be helpful for you to find resources.
