### ISSUE TITLE
site recommendation: alsnhll/SEIR_COVID19

### ISSUE THREAD

**Issue by traversaro** [WeileiZeng/Open-Source-COVID-19#41]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: https://github.com/alsnhll/SEIR_COVID19
  repo2_name:
  web_name: Modeling COVID-19 Spread vs Healthcare Capacity
  web_url: https://alhill.shinyapps.io/COVID19seir/
  web2_name:
  web2_url:
  content:
  tags:

which area the projects is working on? Global or some particular area?

It it is a simulation model, not connected to any particular area.  Discussion on Twitter available at https://twitter.com/alison_l_hill/status/1239072817678823425?s=20 .

**Comment by WeileiZeng** [comment]
Thanks! Added!

**Comment by WeileiZeng** [comment]
I think you can link your website in your readme as well~

**Comment by traversaro** [comment]
> 
> 
> I think you can link your website in your readme as well~

I am not related to the project https://github.com/alsnhll/SEIR_COVID19 .
