### ISSUE TITLE
site recommendation: Are we in lockdown

### ISSUE THREAD

**Issue by thebeardbe** [WeileiZeng/Open-Source-COVID-19#42]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: thebeardbe/areweinlockdown-com
  web_name: Are we in lockdown
  web_url: https://areweinlockdown.com
  content: Trying to gather all information about current restrictions in the different countries
  tags: - crowdsourcing-list
 - lockdown
- countries

which area the projects is working on? Global or some particular area?
Global

**Comment by WeileiZeng** [comment]
Added! Thanks!
