### ISSUE TITLE
site recommendation: covid19 grafana dashboard

### ISSUE THREAD

**Issue by gdassori** [WeileiZeng/Open-Source-COVID-19#44]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: https://github.com/gdassori/covid19_data_miner
  repo2_name:
  web_name: covid19 grafana dashboard
  web_url: https://covid19.chatsubo.it
  web2_name:
  web2_url:
  content: A multisources in-depth dashboard
  tags: data, dashboard

which area the projects is working on? Global or some particular area?

The dashboard is a Grafana Dashboard fueled by multiple sources with detailed data from, new updates every ~ 10 minutes.
It have projections, summaries, a easy to use plugin system.

- US (worldometers \ csse)
- Italy (protezione civile)
- Germany (rki)

**Comment by WeileiZeng** [comment]
Thanks! Added!
Do you also save your data somewhere, or just use it for real-time dashboard?
