### ISSUE TITLE
site recommendation: the2019ncov.com

### ISSUE THREAD

**Issue by sorxrob** [WeileiZeng/Open-Source-COVID-19#45]
repo_name: https://github.com/sorxrob/2019-ncov-frontend
web_name: the2019ncov
web_url: https://the2019ncov.com
content: Map, data and timeline of coronavirus (COVID-19)

which area the projects is working on? Global or some particular area?
Global

**Comment by WeileiZeng** [comment]
Added through https://github.com/sorxrob/2019-ncov-frontend/issues/4
