### ISSUE TITLE
site recommendation: Covid-19 India Tracker

### ISSUE THREAD

**Issue by sydrawat** [WeileiZeng/Open-Source-COVID-19#46]
- repo_name: [sydrawat/covid19.in](https://github.com/sydrawat/covid19.in)
-  web_name: Covid-19 India Tracker
- web_url: [https://covid19-in.netlify.com/](https://covid19-in.netlify.com/)
- content: Minimal webpage to display the most important info, numbers.
- tags: covid-19, nCOV, COVID

Projects is working on a particular area : India

**Comment by WeileiZeng** [comment]
Added!
