### ISSUE TITLE
site recommendation: project name

### ISSUE THREAD

**Issue by seanbonner** [WeileiZeng/Open-Source-COVID-19#47]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: /Safecast/
  repo2_name: 
  web_name: Safecast
  web_url: http://safecast.org
  web2_name:
  web2_url:
  content: Open crowd-sourcing/sensing environmental project that began after the Fukushima meltdown to measure radiation, now doing air quality and assisting on COVID-19 issues with disaster response and community expertise and experience and developing some solutions as well.
  tags:

which area the projects is working on? Global or some particular area? Global.

example:
- repo_name: WeileiZeng/Open-Source-COVID-19
    web_name: Open-Source-COVID-19
    web_url: https://weileizeng.github.io/Open-Source-COVID-19/
    content: A collection of all Open Source project  during COVID-19 开源项目汇总
    tags:
    - navigation
    - crowdsourcing-list

**Comment by WeileiZeng** [comment]
Thanks! Safecast has many repos. Can you names one or two of them, which is mostly related to COVID-19? I will put links for those two repos.

**Comment by WeileiZeng** [comment]
meanwhile, I think I can use two tags: map and api

**Comment by seanbonner** [comment]
Most of the work thus far has been sharing lessons learned and best practices for how to manage the overall situation which has been done as articles on the website and the mailing list. We haven't launched any COVID-19 related software projects yet, but this is forthcoming:
https://github.com/Safecast/covid19map

**Comment by WeileiZeng** [comment]
Got it. Added! future update welcome.
