### ISSUE TITLE
site recommendation: COVID-19 Tracker

### ISSUE THREAD

**Issue by cmdctrlesc** [WeileiZeng/Open-Source-COVID-19#48]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: /JanLikar/covid
  repo2_name:
  web_name: COVID Report
  web_url: https://www.covid-report.com
  web2_name: 
  web2_url:
  content: A map that allows people with COVID-19 to mark their past locations to warn others that might have come into contact with them.
  tags: map

which area the projects is working on? Global or some particular area? Global

example:
- repo_name: WeileiZeng/Open-Source-COVID-19
    web_name: Open-Source-COVID-19
    web_url: https://weileizeng.github.io/Open-Source-COVID-19/
    content: A collection of all Open Source project  during COVID-19 开源项目汇总
    tags:
    - navigation
    - crowdsourcing-list

**Comment by WeileiZeng** [comment]
Added. Thanks!
