### ISSUE TITLE
site recommendation: Coronavirus in Abruzzo - I dati aggiornati

### ISSUE THREAD

**Issue by paagr** [WeileiZeng/Open-Source-COVID-19#49]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name:
  repo2_name:
  web_name: Coronavirus in Abruzzo - I dati aggiornati
  web_url: https://covidabruzzo.it/
  web2_name:
  web2_url:
  content:
  tags:

which area the projects is working on? Global or some particular area?
This project is working on a specific area in Italy: "Abruzzo". 

example:
- repo_name: WeileiZeng/Open-Source-COVID-19
    web_name: Open-Source-COVID-19
    web_url: https://weileizeng.github.io/Open-Source-COVID-19/
    content: A collection of all Open Source project  during COVID-19 开源项目汇总
    tags:
    - navigation
    - crowdsourcing-list

**Comment by WeileiZeng** [comment]
Hi Paagr, Your site is great and helpful! Is it open source?

**Comment by WeileiZeng** [comment]
We currently collect open source projects only. You may also look at lists like
https://github.com/soroushchehresa/awesome-coronavirus
Thanks! Your work is helpful!
