### ISSUE TITLE
project recommendation: covid19-autotest-uns

### ISSUE THREAD

**Issue by matiasmicheletto** [WeileiZeng/Open-Source-COVID-19#52]
- repo_name: https://github.com/matiasmicheletto/covid19-autotest-uns/
- web_url: [not available yet]
- content: [EN] A COVID-19 autotest web app with a configurable decision tree that logs the test result to a database. An administrator panel to set up the decision tree model and a dashboard to analyze the results. [ES-AR] Una aplicación web para autotest de COVID-19 con un árbol de decisión configurable que registra el resultado en una base de datos. Un panel administrador para configurar el arbol de decisión y un tablero para analizar los resultados.
- tags: covid19 autotest, life and academic, data
- area: Argentina, pcia. Buenos Aires, Bahía Blanca, Universidad Nacional del Sur - Región Sanitaria I.

**Comment by WeileiZeng** [comment]
Thanks. I added your repo into  a new South America section. Future updates welcome~
