### ISSUE TITLE
site recommendation: coronavirus_analysis

### ISSUE THREAD

**Issue by jmoldon** [WeileiZeng/Open-Source-COVID-19#55]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name: https://github.com/jmoldon/coronavirus_analysis
  repo2_name:
  web_name: cvid_report
  web_url: https://jmoldon.github.io/coronavirus_analysis/cvid_report.html
  web2_name:
  web2_url:
  content: data visualization, simple short-term prediction per country
  tags:

which area the projects is working on? Global or some particular area? Global

**Comment by WeileiZeng** [comment]
Thanks! Added!
