### ISSUE TITLE
开源项目推荐: 武汉市新冠肺炎疫情防控指挥部发放捐赠物资统计

### ISSUE THREAD

**Issue by nCovCover** [WeileiZeng/Open-Source-COVID-19#6]
**请用如下格式填写，每条目各占一行，替换或者删除对应条目，谢谢**
[武汉市新冠肺炎疫情防控指挥部发放捐赠物资统计]
(https://caysnuts.github.io/monitor/index.html)
物资发放数据可视化，数据来自武汉红会

**其他留言**

**Comment by WeileiZeng** [comment]
谢谢！已经收录。可以参考这个项目

[WeileiZeng/red-cross](https://github.com/WeileiZeng/red-cross) [湖北/武汉红十字 云监工平台](https://weileizeng.github.io/red-cross/) 官网公示数据收集与可视化
