### ISSUE TITLE
site recommendation: COVID-19 Global Cases - Open Source Version

### ISSUE THREAD

**Issue by chschoenenberger** [WeileiZeng/Open-Source-COVID-19#61]
- repo_name: chschoenenberger/covid19_dashboard
  web_name: COVID-19 Global Cases - Open Source Version
  web_url: https://chschoenenberger.shinyapps.io/covid19_dashboard/
  content: A global R shiny dashboard showing the evolution and current state of the COVID-19 pandemic including map, tables, and plots.
  tags: dashboard, visualization

which area the projects is working on? Global or some particular area?
Global, but there is also a version for Switzerland (chschoenenberger/covid19_dashboard_ch & https://chschoenenberger.shinyapps.io/covid19_dashboard_ch/

Thanks for adding

**Comment by WeileiZeng** [comment]
Great. I added the link for Switzerland as well.
