### ISSUE TITLE
CovidAPI.info

### ISSUE THREAD

**Issue by backtrackbaba** [WeileiZeng/Open-Source-COVID-19#62]
- repo_name: [backtrackbaba/covid-api](https://github.com/backtrackbaba/covid-api)

- web_name: [CovidAPI.info](https://covidapi.info)

- content: Blazingly fast, daily updated API's to interact with COVID19 dataset by Johns Hopkins University
  tags: api, data, analysis

which area the projects is working on? Global or some particular area?

Working on global data by empowering developers to build dashboards easily

**Comment by WeileiZeng** [comment]
Thanks! Added!
