### ISSUE TITLE
开源项目推荐: zyq5945/diseasedataanalysis

### ISSUE THREAD

**Issue by zyq5945** [WeileiZeng/Open-Source-COVID-19#63]
repo_name: zyq5945/diseasedataanalysis
    web_name: 疾病数据进行分析查看的HTML5网页项目
    web_url: https://zyq5945.github.io/diseasedataanalysis
    content: 一个数据对疾病数据（目前包含sars和covid19）数据进行HTML5网页显示，包括各省份和市区的详细的病例数，康复数，死亡数，在治数（正在治疗的数量的缩写，即累计病例数减去康复数与死亡数），康复率，死亡率和在治率等数据按日期发展的详细情况显示，还能对各省份和市区的数据进行对比，甚至是省份与市区的数据对比，方便发现一些疾病规律，并使用了Boltzmann模型【y = A2 + (A1-A2)/(1 + exp((x-x0)/dx))】对康复情况进行了数据仿真，也使用简单的一次线性模型【y=kx+b】对死亡情况进行了数据仿真，可以在页面调整仿真参数，并查看修改参数后的仿真结果。

**Comment by WeileiZeng** [comment]
Thanks! Added!
