### ISSUE TITLE
Deposit on Zenodo

### ISSUE THREAD

**Issue by nemobis** [WeileiZeng/Open-Source-COVID-19#67]
I suggest that you deposit this project on Zenodo, to ensure long-term preservation and so that it can be cited and attributed (with a DOI) and everything like every good open data resource.

It should only take a few clicks, with the Zenodo integration, and there's also a community where you can add it:
https://zenodo.org/communities/covid-19/

**Comment by WeileiZeng** [comment]
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3731437.svg)](https://doi.org/10.5281/zenodo.3731437)

Thanks for the suggestions! Added!
