### ISSUE TITLE
site recommendation: covid-19-map-by-region

### ISSUE THREAD

**Issue by openbrian** [WeileiZeng/Open-Source-COVID-19#73]
**Please use the following format. You can leave any of them blank. But a web_name is needed if web_url is provided. Thanks**
- repo_name:https://github.com/openbrian/covid-19-map-by-region
  repo2_name:covid-19-map-by-region
  web_name: COVID-19 cases by county per capita
  web_url: https://openbrian.github.io/covid-19-map-by-region/
  web2_name:
  web2_url:
  content:
  tags:

which area the projects is working on? Global or some particular area?

US, but can be global

**Comment by WeileiZeng** [comment]
Thanks! I added it under US section. Future update welcome.

Is there a way to select a default region, e.g. a link directly go to map for CA?

**Comment by openbrian** [comment]
No, but feel free to submit a feature request
