### ISSUE TITLE
开源项目推荐: 项目名称 or (site recommendation: COVID-Next Pytorch model)

### ISSUE THREAD

**Issue by bfreskura** [WeileiZeng/Open-Source-COVID-19#74]
Hi, 

Inspired by this [repo](https://github.com/lindawangg/COVID-Net), we have open sourced a Pytorch model designed to detect COVID-19 from Xray images. It achieves comparable performance with around 5x less parameters.

Feel free to add it to your site!

**Comment by WeileiZeng** [comment]
Thank for the recommendation. It has been added several days ago!

I am trying to make my page and classification clear. But there are a lot of projects working on various subjects and I never think my page is clear enough. Do you have any feedback that would help you better locate the project you are interested? Thanks.

**Comment by WeileiZeng** [comment]
Some times I need to search the name of a repo to make sure it is in the list or not. Somehow I remove the name of the repo and author to make the page cleaner. Then search the name doesn't work anymore. 
To compromise that, I have all projects in the tag page, with name of author and repo. Then I can search in this page. This works for me, but I guess it is not obvious for users.

**Comment by bfreskura** [comment]
> Thank for the recommendation. It has been added several days ago!
> 
> I am trying to make my page and classification clear. But there are a lot of projects working on various subjects and I never think my page is clear enough. Do you have any feedback that would help you better locate the project you are interested? Thanks.

The project you have listed is COVID-Net, but our project is named COVID-Ne**xt** and is a bit different from the COVID-Net. It is also implemented in Pytorch rather than Tensorflow.

**Comment by WeileiZeng** [comment]
> > Thank for the recommendation. It has been added several days ago!
> > I am trying to make my page and classification clear. But there are a lot of projects working on various subjects and I never think my page is clear enough. Do you have any feedback that would help you better locate the project you are interested? Thanks.
> 
> The project you have listed is COVID-Net, but our project is named COVID-Ne**xt** and is a bit different from the COVID-Net. It is also implemented in Pytorch rather than Tensorflow.

where is your repo?

**Comment by bfreskura** [comment]
I apologize, I have pasted the wrong link. Here you go: https://github.com/velebit-ai/COVID-Next-Pytorch

**Comment by WeileiZeng** [comment]
Thanks! Added.
