### ISSUE TITLE
Please add the following sites ...

### ISSUE THREAD

**Issue by dlobo** [WeileiZeng/Open-Source-COVID-19#75]
1. https://e-vent.mit.edu/
2. http://www.arkadesignstudio.in/dataviz/covid19/Covid19-India-District-DataVizualization.html

**Comment by WeileiZeng** [comment]
Thanks for the information. I added the MIT group under research section.

The Indian map is very informative, however I don't see that it is open source. Please correct me if I am wrong.
You may submit it to this list https://github.com/soroushchehresa/awesome-coronavirus

**Comment by WeileiZeng** [comment]
I am going to close it for now. Future updates are welcome~
