### ISSUE TITLE
site recommendation: Latin America Repository

### ISSUE THREAD

**Issue by ZurMaD** [WeileiZeng/Open-Source-COVID-19#76]
- repo_name: Latin America Covid-19 Data Repository by DSRP
    web_name: -
    web_url: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
    content: Repository with daily updates related to Covid-19 of Latin America (South America)
    api: https://covid19latam.herokuapp.com/
    tags:
    - api
    - covid-19 latin america

which area the projects is working on? Global or some particular area?
Latin America, this list
![image](https://user-images.githubusercontent.com/28235457/78295213-604fbc00-74f1-11ea-8ff5-e3a43581a880.png)

**Comment by WeileiZeng** [comment]
Thanks Added!
