### ISSUE TITLE
site recommendation: SMART-CT-SCAN_BASED-COVID19_VIRUS_DETECTOR

### ISSUE THREAD

**Issue by jeremykohn** [WeileiZeng/Open-Source-COVID-19#78]
- repo_name: JordanMicahBennett/SMART-CT-SCAN_BASED-COVID19_VIRUS_DETECTOR
  web_name: SMART-CT-SCAN_BASED-COVID19_VIRUS_DETECTOR
  web_url: https://github.com/JordanMicahBennett/SMART-CT-SCAN_BASED-COVID19_VIRUS_DETECTOR
  content: An image based CT attempt at coronavirus2019 (covid19) diagnosis.
  tags:
  - research

which area the projects is working on? Global or some particular area?
Global

**Comment by WeileiZeng** [comment]
Thanks Added!
