### ISSUE TITLE
BUG - overlap

### ISSUE THREAD

**Issue by marcos-diniz** [WeileiZeng/Open-Source-COVID-19#79]
screen = 1437x867
![bug](https://user-images.githubusercontent.com/34587699/78405189-56ec4f80-75d6-11ea-8836-2559cbeeeaab.png)

**Comment by WeileiZeng** [comment]
Thanks! Fixed temporarily. 

It used github pages and my ability to modify it is limited. Issues or pull request are welcome!

**Comment by marcos-diniz** [comment]
are these pages made with jekyll?

**Comment by WeileiZeng** [comment]
Yes it is jekyll. I try to change the _layout/default.html, but it show no effect(probably some configuration problem). You are welcome to modify it.
