### ISSUE TITLE
site recommendation: gocoronago

### ISSUE THREAD

**Issue by iamrohitsuthar** [WeileiZeng/Open-Source-COVID-19#81]
- repo_name: iamrohitsuthar/gocoronago
  repo2_name: 
  web_name: gocoronago
  web_url: https://gocoronago.ml
  web2_name:
  web2_url:
  content: Website which shows the latest COVID-19 stats in India.
  tags:

which area the projects is working on? Global or some particular area?
India

**Comment by WeileiZeng** [comment]
thanks. Added!
