### ISSUE TITLE
Contributing to Open-Source-COVID-19

### ISSUE THREAD

**Issue by paras-jain** [WeileiZeng/Open-Source-COVID-19#83]
How can we contribute to the site, adding other open source sources?

**Comment by WeileiZeng** [comment]
Yes, that would be great! My school just started and I almost stop updating this week.

The data file is in _data folder and explained here https://github.com/WeileiZeng/Open-Source-COVID-19/blob/master/_data/readme.md Just edit those file and send pull request! If you update more frequently, I can add you as a collaborator as well.

There is a search tool to make it easier to find new sites, which updates automatically every day.
http://open-source-covid-19.weileizeng.com/search

Thanks in advance!

**Comment by paras-jain** [comment]
That'd be cool. Thanks!
