### ISSUE TITLE
site recommendation

### ISSUE THREAD

**Issue by paras-jain** [WeileiZeng/Open-Source-COVID-19#85]
It would be good to have a CONTRIBUTING.md file with all the contributing guidelines and such, which can be linked in at the README.

**Comment by WeileiZeng** [comment]
Hi I just added it! Let me know if it is unclear.

https://github.com/WeileiZeng/Open-Source-COVID-19/blob/master/contribute.md

**Comment by paras-jain** [comment]
Looks cool. I beautified it  bit and proposed some minor changes. Kindly review the PR.
