### ISSUE TITLE
site recommendation: RID-COVID

### ISSUE THREAD

**Issue by jeremykohn** [WeileiZeng/Open-Source-COVID-19#86]
- repo_name: jeremykohn/rid-covid
  web_name: RID-COVID: Radiological Image Data for Clinical Open-source Viral Infection Diagnosis
  web_url: https://github.com/jeremykohn/rid-covid
  content: Software, datasets, and other resources for diagnosing COVID-19 based on X-rays and CT scans.
  tags: 
  - crowdsourced-list 
  - research 
  - data 
  - AI

which area the projects is working on? Global or some particular area?
- Global

**Comment by WeileiZeng** [comment]
Thanks! Added!
