### ISSUE TITLE
site recommendation: coronavirus package dataset

### ISSUE THREAD

**Issue by gitgudyyao** [WeileiZeng/Open-Source-COVID-19#99]
- repo_name: RamiKrispin/coronavirus
  repo2_name:
  web_name: The 2019 Novel Coronavirus COVID-19 Dataset
  web_url: ramikrispin.github.io/coronavirus/
  web2_name:
  web2_url:
  content: The coronavirus package provides a tidy format dataset of the 2019 Novel Coronavirus COVID-19 (2019-nCoV) epidemic. The raw data pulled from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus repository.
  tags:
-API
-data

**Comment by WeileiZeng** [comment]
Thanks, added!
